version: "3.1"

networks:
  mq-backend:

volumes:
  config:
    driver_opts:
      type: ${VOLUME_TYPE}-config
      o: ${CONFIG_OPTS}
      device: ${NEON_CONFIG_PATH}
    labels:
      kompose.volume.storage-class-name: nfs-config
  metrics:
    driver_opts:
      type: ${VOLUME_TYPE}-metrics
      o: ${METRIC_OPTS}
      device: ${NEON_METRIC_PATH}
    labels:
      kompose.volume.storage-class-name: nfs-metrics
