version: "0.0.1"

services:
  neon_rabbitmq:
    container_name: neon_rabbitmq
    hostname: neon_rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ${NEON_CONFIG_PATH}/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${NEON_CONFIG_PATH}:/config
  neon_api_proxy:
    container_name: neon_api_proxy
    hostname: neon_api_proxy
    image: ghcr.io/neongeckocom/neon_api_proxy:dev
    restart: unless-stopped
    links:
      - neon_rabbitmq
    volumes:
      - ${NEON_CONFIG_PATH}:/config
  neon_brands_service:
    container_name: neon_brands_service
    hostname: neon_brands_service
    image: ghcr.io/neongeckocom/neon_brands_service:dev
    restart: unless-stopped
    links:
      - neon_rabbitmq
    volumes:
      - ${NEON_CONFIG_PATH}:/config
  neon_email_proxy:
    container_name: neon_email_proxy
    hostname: neon_email_proxy
    image: ghcr.io/neongeckocom/neon_email_proxy:dev
    restart: unless-stopped
    links:
      - neon_rabbitmq
    volumes:
      - ${NEON_CONFIG_PATH}:/config
  neon_script_parser:
    container_name: neon_script_parser
    hostname: neon_script_parser
    image: ghcr.io/neongeckocom/neon-script-parser:dev
    restart: unless-stopped
    links:
      - neon_rabbitmq
    volumes:
      - ${NEON_CONFIG_PATH}:/config
  neon_metrics_service:
    container_name: neon_metrics_service
    hostname: neon_metrics_service
    image: ghcr.io/neongeckocom/neon_metrics_service:dev
    restart: unless-stopped
    links:
      - neon_rabbitmq
    volumes:
      - ${NEON_CONFIG_PATH}:/config
      - ${NEON_METRIC_PATH}:/metrics
