version: "3.1"

networks:
  mq-backend:

volumes:
  config:
    driver_opts:
      type: ${VOLUME_TYPE}
      o: ${CONFIG_OPTS}
      device: ${NEON_CONFIG_PATH}
  metrics:
    driver_opts:
      type: ${VOLUME_TYPE}
      o: ${METRIC_OPTS}
      device: ${NEON_METRIC_PATH}
