apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: config
    spec:
      capacity:
        storage: 1Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: nfs-config
      mountOptions:
        - nolock
        - rw
        - soft
        - "nfsvers=4"
      nfs:
        path: ${CONFIG_PATH}
        server: ${HOST}
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: metrics
    spec:
      capacity:
        storage: 10Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: nfs-metrics
      mountOptions:
        - nolock
        - rw
        - soft
        - "nfsvers=4"
      nfs:
        path: ${METRIC_PATH}
        server: ${HOST}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config
      name: config
    spec:
      storageClassName: nfs-config
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: metrics
      name: metrics
    spec:
      storageClassName: nfs-metrics
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
    status: {}