serviceName: neon-core-speech
replicaCount: 1
configMap: neon-config
image:
  repository: ghcr.io/neongeckocom/neon_speech
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "1Gi"
    cpu: "0.1"