apiVersion: v2
name: tts-ljspeech
description: Deploy a LJSpeech TTS Server

type: application
version: 0.0.1
appVersion: "1.0.1a4"

dependencies:
  - name: base-http
    version: 0.0.2
    repository: file://../base-http