serviceName: backend-mq-brands-service
replicaCount: 1
configSecret: diana-config
image:
  pullSecret: github-auth
  repository: ghcr.io/neongeckocom/neon_brands_service
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "50Mi"
    cpu: "0.01"