serviceName: neon-core-messagebus
replicaCount: 1
configMap: neon-config
port:
  name: messagebus
  number: 8181
  targetPort: 8181
image:
  repository: ghcr.io/neongeckocom/neon_messagebus
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "500Mi"
    cpu: "0.1"
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /status
    port: 8000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  failureThreshold: 30
  httpGet:
    path: /status
    port: 8000
    scheme: HTTP
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

