# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

rabbitmq:
  commonLabels:
    neon.project.name: diana
    neon.diana.service: rabbitmq
    neon.service.class: communication
  auth:
    username: neon
    password: neon

  image:
    debug: true

ingress:
  enabled: True
  hostname: mqadmin.diana.local
  ingressClassName: nginx
  tlsSecretName: tls-letsencrypt-prod