apiVersion: v2
name: tts-coqui
description: Deploy a Coqui TTS Server

type: application
version: 0.0.5
appVersion: "1.0.1a17"

dependencies:
  - name: base-http
    version: 0.0.5
    repository: file://../../base/base-http