apiVersion: v2
name: brainforge-llm-service
description: Deploy a Brainforge LLM Backend Service

type: application
version: 0.0.1
appVersion: "1.0.1a29"

dependencies:
  - name: base-mq
    version: 0.0.10
    repository: file://../../base/base-mq