serviceName: neon-core-gui
replicaCount: 1
configMap: neon-config
port:
  name: gui
  number: 18181
  targetPort: 18181
image:
  repository: ghcr.io/neongeckocom/neon_gui
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "100Mi"
    cpu: "0.01"