replicaCount: 1
imagePullSecret: github-auth
serviceName: klat-chat
domain: diana.k8s
configMap: klat-config
clientSubdomain: klat
serverSubdomain: klatapi
adminSubdomain: klatadmin
images:
  tag: &image_tag dev
  pullPolicy: Always
  client:
    image: ghcr.io/neongeckocom/pyklatchat-client
    name: klat-chat-client
    tag: *image_tag
  server:
    image: ghcr.io/neongeckocom/pyklatchat-server
    name: klat-chat-server
    tag: *image_tag
  observer:
    image: ghcr.io/neongeckocom/pyklatchat-observer
    name: klat-chat-observer
    tag: *image_tag
  admin:
    image: ghcr.io/neongeckocom/pyklatchat_admin
    name: klat-chat-admin
    tag: *image_tag
resources:
  requests:
    memory: "500Mi"
    cpu: "0.01"

ingress:
  enabled: True
  ingressClassName: nginx
  tlsSecretName: tls-letsencrypt-klat
  certIssuer: letsencrypt-private-key
  redirectRoot: False
  rules:
    - host: klat
      serviceName: klat-chat-client
      servicePort: 8001
    - host: klatapi
      serviceName: klat-chat-server
      servicePort: 8010
    - host: klatadmin
      serviceName: klat-chat-admin
      servicePort: 3000