apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      neon.diana.service: {{ .Chart.Name }}-client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        neon.diana.service: {{ .Chart.Name }}-client
        neon.project.name: klat
        neon.service.class: klat-chat
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{ .Values.configMap }}
      containers:
        - image: {{ .Values.images.client.image }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ $.Values.images.pullPolicy }}
          name: {{ .Values.images.client.name }}
          env:
            - name: OVOS_CONFIG_FILENAME
              value: klat.yaml
            - name: OVOS_CONFIG_BASE_FOLDER
              value: neon
            - name: XDG_CONFIG_HOME
              value: /config
            - name: CORS_ALLOWED_ORIGINS
              value: https://klatapi.{{ .Values.domain }}
            - name: LOG_LEVEL
              value: DEBUG
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "8001"
          volumeMounts:
            - name: config
              mountPath: /config/neon/{{ $.Values.configFilename }}
              subPath: {{ $.Values.configFilename }}
          {{- if $.Values.resources }}
          resources:
          {{- toYaml $.Values.resources | nindent 12 -}}
        {{ end }}