apiVersion: v2
name: ww-snowboy
description: Deploy Snowboy Wake Word Trainer

type: application
version: 0.0.1
appVersion: "1.0.1a6"

dependencies:
  - name: base-http
    version: 0.0.2
    repository: https://neongeckocom.github.io/neon-diana-utils