apiVersion: v1
kind: Service
metadata:
  labels:
    neon.project.name: klat
    neon.diana.service: {{ .Values.serviceName }}
    neon.service.class: klat-observer
  name: {{ .Values.serviceName }}-observer
spec:
  clusterIP: None
  selector:
    neon.diana.service: {{ .Values.serviceName }}-observer
  ports:
    - name: headless
      port: 55555
      targetPort: 0