apiVersion: v1
kind: Service
metadata:
  labels:
    neon.project.name: klat
    neon.diana.service: {{ .Values.serviceName }}
    neon.service.class: klat-server
  name: {{ .Values.serviceName }}-server
spec:
  type: ClusterIP
  selector:
    neon.diana.service: {{ .Values.serviceName }}-server
  ports:
    - name: klat-server
      port: 8010
      targetPort: 8010
      protocol: TCP
