apiVersion: v1
kind: Service
metadata:
  labels:
    neon.project.name: klat
    neon.diana.service: {{ .Values.serviceName }}
    neon.service.class: klat-admin
  name: {{ .Values.serviceName }}-admin
spec:
  type: ClusterIP
  selector:
    neon.diana.service: {{ .Values.serviceName }}-admin
  ports:
    - name: klat-admin
      port: 3000
      targetPort: 3000
      protocol: TCP
