serviceName: backend-llm-chatgpt
replicaCount: 1
configSecret: diana-config
image:
  repository: ghcr.io/neongeckocom/neon-llm-chatgpt
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "600Mi"
    cpu: "0.01"
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /status
    port: 8000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

