apiVersion: v2
name: neon-core
description: Deploy Neon Core Services

type: application
version: 0.0.4
appVersion: "1.0.1a7"
dependencies:
  - name: neon-messagebus
    alias: neon-messagebus
    version: 0.0.4
    repository: file://../neon-messagebus
  - name: neon-speech
    alias: neon-speech
    version: 0.0.4
    repository: file://../neon-speech
  - name: neon-skills
    alias: neon-skills
    version: 0.0.4
    repository: file://../neon-skills
  - name: neon-audio
    alias: neon-audio
    version: 0.0.4
    repository: file://../neon-audio
  - name: neon-enclosure
    alias: neon-enclosure
    version: 0.0.4
    repository: file://../neon-enclosure
  - name: neon-gui
    alias: neon-gui
    version: 0.0.4
    repository: file://../neon-gui