imageTag: &tag dev
configMap: neon-config
neonConfig: {}
neon-messagebus:
  image:
    tag: *tag
neon-speech:
  image:
    tag: *tag
neon-skills:
  image:
    tag: *tag
neon-audio:
  image:
    tag: *tag
neon-enclosure:
  image:
    tag: *tag
neon-gui:
  image:
    tag: *tag
iris-gradio:
  ingress:
    enabled: False

domain: diana.local
ingress:
  enabled: True
  ingressClassName: nginx
  tlsSecretName: tls-letsencrypt-iris
  certIssuer: letsencrypt-private-key
  rules:
    - host: iris
      serviceName: neon-core-iris
      servicePort: 7860
    # Define ingress rules for any available web UIs that may be enabled here