{{- $_diana_config := .Files.Get "diana.yaml" | b64enc -}}
{{ $_ := set .Values.backend "dianaConfig" $_diana_config }}
{{- include "diana_config.secret" . }}
---
{{- $_rabbitmq_config := .Files.Get "rabbitmq.json" | b64enc -}}
{{ $__ := set .Values.backend "rabbitMqConfig" $_rabbitmq_config }}
{{- include "diana_rabbitmq.secret" . }}
---
{{- $_google_config := .Files.Get "google.json" | b64enc -}}
{{ $___ := set .Values.backend "googleJson" $_google_config }}
{{- include "google_json.secret" . }}
