apiVersion: v1
kind: Service
metadata:
  labels:
    neon.project.name: chatbots
    neon.diana.service: {{ default .Chart.Name .Values.serviceName }}
    neon.service.class: facilitators
  name: {{ default .Chart.Name .Values.serviceName }}
spec:
  clusterIP: None
  selector:
    neon.diana.service: {{ default .Chart.Name .Values.serviceName }}
  ports:
    - name: headless
      port: 55555
      targetPort: 0
