apiVersion: v2
name: neon-llm-fastchat
description: Deploy an LLM proxy for FastChat

type: application
version: 0.0.6
appVersion: "1.0.1a20"

dependencies:
  - name: base-mq
    version: 0.0.10
    repository: file://../../base/base-mq