apiVersion: v2
name: neon-speech
description: Deploy Neon Core Speech (Voice) Service

type: application
version: 0.0.1
appVersion: "1.0.1a4"

dependencies:
  - name: base-neon
    version: 0.0.1
    repository: file://../base-neon