apiVersion: v2
name: diana-mq
description: Deploy DIANA MQ Services

type: application
version: 0.0.17
appVersion: "1.0.1a22"
dependencies:
  - name: neon-api-proxy
    alias: neon-api-proxy
    version: 0.0.6
    repository: file://../../mq/neon-api-proxy
  - name: neon-brands-service
    alias: neon-brands-service
    version: 0.0.6
    repository: file://../../mq/neon-brands-service
  - name: neon-email-proxy
    alias: neon-email-proxy
    version: 0.0.6
    repository: file://../../mq/neon-email-proxy
  - name: neon-metrics-service
    alias: neon-metrics-service
    version: 0.0.7
    repository: file://../../mq/neon-metrics-service
  - name: neon-script-parser
    alias: neon-script-parser
    version: 0.0.6
    repository: file://../../mq/neon-script-parser
  - name: neon-llm-chatgpt
    alias: neon-llm-chatgpt
    version: 0.0.7
    repository: file://../../mq/neon-llm-chatgpt
  - name: neon-llm-fastchat
    alias: neon-llm-fastchat
    version: 0.0.6
    repository: file://../../mq/neon-llm-fastchat
  - name: neon-llm-claude
    alias: neon-llm-claude
    version: 0.0.2
    repository: file://../../mq/neon-llm-claude
  - name: neon-llm-gemini
    alias: neon-llm-gemini
    version: 0.0.2
    repository: file://../../mq/neon-llm-gemini
  - name: neon-llm-palm
    alias: neon-llm-palm
    version: 0.0.6
    repository: file://../../mq/neon-llm-palm
