serviceName: neon-core-audio
replicaCount: 1
configMap: neon-config
image:
  repository: ghcr.io/neongeckocom/neon_audio
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "300Mi"
    cpu: "0.1"
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /status
    port: 8000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  failureThreshold: 30
  httpGet:
    path: /status
    port: 8000
    scheme: HTTP
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

