apiVersion: v2
name: stt-fasterwhisper
description: Deploy a FasterWhisper STT Server

type: application
version: 0.0.1
appVersion: "1.0.1a23"

dependencies:
  - name: base-http
    version: 0.0.6
    repository: file://../../base/base-http
