apiVersion: v1
kind: Service
metadata:
  labels:
    neon.project.name: diana
    neon.diana.service: {{ .Chart.Name }}
    neon.service.class: http
  name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service_port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    neon.diana.service: {{ .Chart.Name }}