serviceName: backend-llm-vllm
replicaCount: 1
configSecret: diana-config
image:
  repository: ghcr.io/neongeckocom/neon-llm-vllm
  pullPolicy: Always
  tag: dev
resources:
  requests:
    memory: "1Gi"
    cpu: "1.0"
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /status
    port: 8000
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

