apiVersion: v1
kind: Service
metadata:
  labels:
    neon.project.name: chatbots
    neon.diana.service: {{ .Chart.Name }}
    neon.service.class: facilitators
  name: {{ .Chart.Name }}
spec:
  clusterIP: None
  selector:
    neon.diana.service: {{ .Chart.Name }}
  ports:
    - name: headless
      port: 55555
      targetPort: 0
