replicaCount: 1
serviceName: cbf-facilitators
configMap: chatbots-config
configFilename: chatbots.yaml
images:
  pullPolicy: Always
  tag: "dev"
  containers:
    - image: "ghcr.io/neongeckocom/mq-chatbots-observer"
      name: "chatbots-observer"
    - image: "ghcr.io/neongeckocom/chat-facilitator-automator"
      name: "chat-automator"
    - image: "ghcr.io/neongeckocom/chat-facilitator-context_keeper"
      name: "context-keeper"
    - image: "ghcr.io/neongeckocom/chat-facilitator-proctor"
      name: "proctor"
    - image: "ghcr.io/neongeckocom/chat-facilitator-scorekeeper"
      name: "scorekeeper"
    - image: "ghcr.io/neongeckocom/chat-facilitator-stenographer"
      name: "stenographer"
