# This workflow will run unit tests

name: Run Unit Tests
on:
  push:
  workflow_dispatch:

jobs:
  test_api:
    runs-on: ubuntu-latest
    env:
      NEON_CONFIG_PATH: ~/config
      NEON_METRIC_PATH: ~/metrics
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Start Docker MQ service
        run: |
          docker-compose up neon_rabbitmq
      - name: Configure Neon Diana Server
        - python setup_default_server.py
      - name: Start Docker Diana Services
        run: |
          docker-compose up
      - name: Test with pytest
        run: |
          pip install pytest pytest-timeout pytest-cov
          pytest tests/test_script_parser.py --doctest-modules --junitxml=tests/test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/test-results.xml