name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/test_requirements.txt
      - name: Run Utils Tests
        run: |
          pytest tests/test_diana_utils.py --doctest-modules --junitxml=tests/utils-test-results.xml
      - name: Upload Utils test results
        uses: actions/upload-artifact@v2
        with:
          name: utils-test-results
          path: tests/utils-test-results.xml
      - name: Run Constants Tests
        run: |
          pytest tests/test_constants.py --doctest-modules --junitxml=tests/constants-test-results.xml
      - name: Upload Constants test results
        uses: actions/upload-artifact@v2
        with:
          name: constants-test-results
          path: tests/constants-test-results.xml
      - name: Run Service Tests
        run: |
          pytest tests/test_diana_services.py --doctest-modules --junitxml=tests/services-test-results.xml
      - name: Upload Services test results
        uses: actions/upload-artifact@v2
        with:
          name: services-test-results
          path: tests/services-test-results.xml