name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements/test_requirements.txt
      - name: Run Tests
        run: |
          pytest tests --doctest-modules --junitxml=tests/diana-test-results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: utils-test-results
          path: tests/diana-test-results.xml
